version: "2.1"
services:
  sa-event-ms:
    container_name: sa-event-ms
    build: .
    ports:
      - "4000:8000"
    depends_on:
      sa-event-db:
        condition: service_healthy
    environment:
      MONGO_HOST: 172.17.0.1
      MONGO_PORT: 27018
    healthcheck:
      test: "curl -G localhost:8000/event --fail"
      interval: 20s
      retries: 10
  sa-event-db:
    container_name: sa-event-db
    image: mongo
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 20s
      timeout: 5s
      retries: 3
    ports:
      - "27018:27017"
